### ISSUE TITLE
TestAssertPath_Directive fails at go test

### ISSUE THREAD

**Issue by rogers0** [viant/assertly#4]
Hi there,

I'm working with @creekorful to package this project into Debian.
Debian build system usually run go test after building the package, so I find TestAssertPath_Directive fails.
Here's the log:

=== RUN   TestAssertPath_Directive
directive_test.go:192 (TestAssertPath_Directive)
[/]:[1].SubPath: actual(string): 'group1.field3' was not equal (string) 'group1.field2'
directive_test.go:192 (TestAssertPath_Directive)
[/]:[1].Expected: actual(int): '3' was not equal (int) '2'
directive_test.go:192 (TestAssertPath_Directive)
[/]:[2].SubPath: actual(string): 'group1.field2' was not equal (string) 'group1.field3'
directive_test.go:192 (TestAssertPath_Directive)
[/]:[2].Expected: actual(int): '2' was not equal (int) '3'
--- FAIL: TestAssertPath_Directive (0.00s)

Full build log can be referenced:
- https://buildd.debian.org/status/fetch.php?pkg=golang-github-viant-assertly&arch=all&ver=0.5.3-2&stamp=1592566567&raw=0

Thank you!

**Comment by adranwit** [comment]
I can see this test intermittently fails, looking into

**Comment by adranwit** [comment]
Patched intermittently passing test in master,  once you confirm I will create a new tag

**Comment by rogers0** [comment]
Dear @adranwit 

Thanks for your prompt fix!
Yes, I confirm your latest master branch fixes this issue.
