### ISSUE TITLE
A few warnings (but log shows fail) at go test

### ISSUE THREAD

**Issue by rogers0** [viant/assertly#5]
Hi there,

I'm working with @creekorful to package this project into Debian.
Debian build system usually run go test after building the package, so I find a few warnings (log shows fails, but result is Passed).
Here's the log:

=== RUN   TestAssertMap
2020/06/19 11:36:03 failed to apply directive to actual actual value: parsing time "99-99-99" as "2006-01-": cannot parse "9-99" as "2006"
--- PASS: TestAssertMap (0.00s)
=== RUN   TestAssertStructureWithIndexDirective
[/]:2.name: actual(string): 'name 22' was not equal (string) 'name 2'
Passed: 5
Failed: 1
--- PASS: TestAssertStructureWithIndexDirective (0.00s)
=== RUN   TestAssertNumericPrecission
--- PASS: TestAssertNumericPrecission (0.00s)
=== RUN   TestAssertCoalesceWithZero
[/]:[0].tac: actual(<nil>): '<nil>' was not equal (int) '0'
Passed: 0
Failed: 1
--- PASS: TestAssertCoalesceWithZero (0.00s)
=== RUN   TestAssertCaseSensitive
[/]:[0].tac: actual(string): 'abc' was not equal (string) 'ABC'
Passed: 0
Failed: 1
--- PASS: TestAssertCaseSensitive (0.00s)
=== RUN   TestAssertMultiIndexBy
--- PASS: TestAssertMultiIndexBy (0.00s)
=== RUN   TestAssertStructureWithSource
[/]:2.name: actual(string): 'name 22' was not equal (string) 'name 2'
Passed: 5
Failed: 1
--- PASS: TestAssertStructureWithSource (0.00s)

Full build log can be referenced:
- https://buildd.debian.org/status/fetch.php?pkg=golang-github-viant-assertly&arch=all&ver=0.5.3-2&stamp=1592566567&raw=0

Thank you!

**Comment by adranwit** [comment]
Hi, 
Assertly is rule-based test library, so all the output PASSED/FAILED are produced as part of the test, 
I see all test passing, 

In your build, are you scraping 'failed' fragment or you are checking the exit command status ?

**Comment by rogers0** [comment]
Dear @adranwit 

Yes, test was all passed, so I reported this as "warning".

```
2020/06/19 11:36:03 failed to apply directive to actual actual value: parsing time "99-99-99" as "2006-01-": cannot parse "9-99" as "2006"
[/]:2.name: actual(string): 'name 22' was not equal (string) 'name 2'
[/]:[0].tac: actual(): '' was not equal (int) '0'
[/]:[0].tac: actual(string): 'abc' was not equal (string) 'ABC'
[/]:2.name: actual(string): 'name 22' was not equal (string) 'name 2'
```

If above warnings are all expected, I think we can safely close this ticket.
Thank you!
